// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: public_member_api_docs, prefer_single_quotes, avoid_escaping_inner_quotes, prefer_const_constructors, sort_constructors_first, always_specify_types

import 'dart:async';

import 'package:flutter/widgets.dart';

/// A class generated by flappy_translator package containing localized strings
class I18n {
  String get current_language => _getText("current_language");

  String get uses => _getText("uses");

  String get uses_total => _getText("uses_total");

  String get users => _getText("users");

  String get traps => _getText("traps");

  String get traps_occupied => _getText("traps_occupied");

  String get last_seven_days => _getText("last_seven_days");

  String get new_ => _getText("new_");

  String get usage_logs => _getText("usage_logs");

  String get name => _getText("name");

  String get log_out => _getText("log_out");

  String get search => _getText("search");

  String get place_alias => _getText("place_alias");

  String get number_of_uses => _getText("number_of_uses");

  String get description => _getText("description");

  String get logs => _getText("logs");

  String get add_new => _getText("add_new");

  String get language => _getText("language");

  String get edit_trap => _getText("edit_trap");

  String get how_create_new_trap => _getText("how_create_new_trap");

  String get new_trap => _getText("new_trap");

  String get trap_name => _getText("trap_name");

  String get required_name => _getText("required_name");

  String get max_letters => _getText("max_letters");

  String get required_description => _getText("required_description");

  String get save => _getText("save");

  String get new_trap_successfully => _getText("new_trap_successfully");

  String get monday => _getText("monday");

  String get tuesday => _getText("tuesday");

  String get wednesday => _getText("wednesday");

  String get thursday => _getText("thursday");

  String get friday => _getText("friday");

  String get saturday => _getText("saturday");

  String get sunday => _getText("sunday");

  String get available => _getText("available");

  String get occupied => _getText("occupied");

  String get create_report => _getText("create_report");

  String get create_at => _getText("create_at");

  String get opened => _getText("opened");

  String get closed => _getText("closed");

  String get of_use => _getText("of_use");

  String get main_start => _getText("main_start");

  String get new_trap_continue => _getText("new_trap_continue");

  String get new_trap_previous => _getText("new_trap_previous");

  String get new_trap_definetrap => _getText("new_trap_definetrap");

  String get new_trap_selectfirst => _getText("new_trap_selectfirst");

  String get new_trap_selectsecond => _getText("new_trap_selectsecond");

  String get new_trap_selectthird => _getText("new_trap_selectthird");

  String get new_trap_selectfour => _getText("new_trap_selectfour");

  String get new_trap_endtrap => _getText("new_trap_endtrap");

  String get new_trap_associate_lock => _getText("new_trap_associate_lock");

  String get new_trap_unassociate_lock => _getText("new_trap_unassociate_lock");

  String get new_trap_lock_name => _getText("new_trap_lock_name");

  String get new_trap_lock_mac => _getText("new_trap_lock_mac");

  String get new_trap_lock_data => _getText("new_trap_lock_data");

  String get new_trap_lock_associate => _getText("new_trap_lock_associate");

  String get new_trap_lock_open => _getText("new_trap_lock_open");

  String get new_trap_lock_close => _getText("new_trap_lock_close");

  String get locks_name => _getText("locks_name");

  String get login_init => _getText("login_init");

  String get dialog_attention => _getText("dialog_attention");

  String get recover_change => _getText("recover_change");

  String get recover_title => _getText("recover_title");

  String get recover_email => _getText("recover_email");

  String get recover_new_password => _getText("recover_new_password");

  String get recover_hint => _getText("recover_hint");

  String get recover_otp_email => _getText("recover_otp_email");

  String get recover_otp_confirm_email => _getText("recover_otp_confirm_email");

  String get recover_go => _getText("recover_go");

  String get recover_otp => _getText("recover_otp");

  String get recover_otp_help => _getText("recover_otp_help");

  String get check_email => _getText("check_email");

  String get check_otp => _getText("check_otp");

  String get check_password => _getText("check_password");

  String get check_password_confirm => _getText("check_password_confirm");

  String get change_password => _getText("change_password");

  String get exit_title => _getText("exit_title");

  String get exit_message => _getText("exit_message");

  String get dialog_ok => _getText("dialog_ok");

  String get dialog_cancel => _getText("dialog_cancel");

  String get dialog_sucess => _getText("dialog_sucess");

  String get login_title => _getText("login_title");

  String get login_message => _getText("login_message");

  String get login_recover => _getText("login_recover");

  String get login_register => _getText("login_register");

  String get login_login => _getText("login_login");

  String get textfield_name => _getText("textfield_name");

  String get textfield_email => _getText("textfield_email");

  String get textfield_password => _getText("textfield_password");

  String get textfield_telephone => _getText("textfield_telephone");

  String get textfield_confirmpassword => _getText("textfield_confirmpassword");

  static late Map<String, String> _localizedValues;

  static const _esValues = {
    "current_language": "es",
    "uses": "Usos",
    "uses_total": "Usos totales",
    "users": "Usuarios",
    "traps": "Traps",
    "traps_occupied": "Traps ocupados",
    "last_seven_days": "Últimos 7 días",
    "new_": "Nuevos",
    "usage_logs": "Registros de uso",
    "name": "Nombre",
    "log_out": "Cerrar sesión",
    "search": "Buscar",
    "place_alias": "Alias/Lugar",
    "number_of_uses": "Nº de usos",
    "description": "Descripción",
    "logs": "Usos",
    "add_new": "Agregar Nuevo",
    "language": "Lenguaje",
    "edit_trap": "Editar trap/soca",
    "how_create_new_trap": "Mantén presionado para nuevo trap",
    "new_trap": "Nuevo trap",
    "trap_name": "Nombre del Trap (Alias o Lugar)",
    "required_name": "El nombre es requerido",
    "max_letters": "Max 30 caracteres",
    "required_description": "La descripción es requerida",
    "save": "Guardar",
    "new_trap_successfully": "Trap nuevo creado correctamente",
    "monday": "L",
    "tuesday": "M",
    "wednesday": "X",
    "thursday": "J",
    "friday": "V",
    "saturday": "S",
    "sunday": "D",
    "available": "Disponible",
    "occupied": "Ocupado",
    "create_report": "Crear reporte",
    "create_at": "Creado el",
    "opened": "Abierto",
    "closed": "Cerrado",
    "of_use": "de uso",
    "main_start": "Iniciar",
    "new_trap_continue": "continuar",
    "new_trap_previous": "anterior",
    "new_trap_definetrap": "Defina el nombre y el nombre de la ubicación",
    "new_trap_selectfirst": "Configure el primer cierre",
    "new_trap_selectsecond": "Configure el segundo cierre",
    "new_trap_selectthird": "Configure el tercer cierre",
    "new_trap_selectfour": "configure el cuarto cierre",
    "new_trap_endtrap": "Guardar datos del trap",
    "new_trap_associate_lock": "Associar Lock",
    "new_trap_unassociate_lock": "Desassociar Lock",
    "new_trap_lock_name": "Nombre cierre",
    "new_trap_lock_mac": "Mac cierre",
    "new_trap_lock_data": "LockData",
    "new_trap_lock_associate": "Associar",
    "new_trap_lock_open": "Abrir",
    "new_trap_lock_close": "Cerrar",
    "locks_name": "Cierres",
    "login_init": "Iniciar",
    "dialog_attention": "Atención",
    "recover_change": "Salvar",
    "recover_title": "Recuperar contraseña",
    "recover_email": "Correo",
    "recover_new_password": "Nueva contraseña",
    "recover_hint": "Introduce tu correo",
    "recover_otp_email": "Introduzca nueva contraseña",
    "recover_otp_confirm_email": "Confirme contraseña",
    "recover_go": "Recuperar",
    "recover_otp": "Introduce tu contraseña temporal",
    "recover_otp_help": "Se ha enviado un email con una contraseña temporal",
    "check_email": "Introduzca email",
    "check_otp": "Introduzca el código único",
    "check_password": "Introduzca la contraseña",
    "check_password_confirm": "Confirma la contraseña",
    "change_password": "Cambio de contraseña correcto",
    "exit_title": "Atención",
    "exit_message": "Vas a salir de Yup.city",
    "dialog_ok": "Aceptar",
    "dialog_cancel": "Cancelar",
    "dialog_sucess": "¡Éxito!",
    "login_title": "Hey",
    "login_message": "¡Me alegro\n de verte!",
    "login_recover": "Recuperar contraseña",
    "login_register": "Registro",
    "login_login": "Iniciar",
    "textfield_name": "Nombre",
    "textfield_email": "Email",
    "textfield_password": "Contraseña",
    "textfield_telephone": "Teléfono",
    "textfield_confirmpassword": "Confirmar Contraseña",
  };

  static const _enValues = {
    "current_language": "en",
    "uses": "Uses",
    "uses_total": "Total of uses",
    "users": "Users",
    "traps": "Traps",
    "traps_occupied": "Occupied Trap",
    "last_seven_days": "Last 7 days",
    "new_": "New",
    "usage_logs": "Usage logs",
    "name": "Name",
    "log_out": "Log out",
    "search": "Search",
    "place_alias": "Alias/Place",
    "number_of_uses": " Nº of uses",
    "description": "Description",
    "logs": "Logs",
    "add_new": "Add New",
    "language": "Language",
    "edit_trap": "Edit trap/soca",
    "how_create_new_trap": "Long press to create a new trap",
    "new_trap": "New trap",
    "trap_name": "Trap's name (nick name or center)",
    "required_name": "Trap's name is required",
    "max_letters": "Max 30 characters",
    "required_description": "Description field is required",
    "save": "Save",
    "new_trap_successfully": "New trap created successfully",
    "monday": "Mo",
    "tuesday": "Tu",
    "wednesday": "We",
    "thursday": "Th",
    "friday": "Fr",
    "saturday": "Sa",
    "sunday": "Su",
    "available": "Available",
    "occupied": "Occupied",
    "create_report": "Create Report",
    "create_at": "Create at",
    "opened": "Opened",
    "closed": "Closed",
    "of_use": "of use",
    "main_start": "Start",
    "new_trap_continue": "continue",
    "new_trap_previous": "previous",
    "new_trap_definetrap": "Define the name and location name",
    "new_trap_selectfirst": "Configure first lock",
    "new_trap_selectsecond": "Configure second lock",
    "new_trap_selectthird": "Configure third lock",
    "new_trap_selectfour": "Configure fourth lock",
    "new_trap_endtrap": "Save trap data",
    "new_trap_associate_lock": "Bind Lock",
    "new_trap_unassociate_lock": "Unbind Lock",
    "new_trap_lock_name": "Lock Name",
    "new_trap_lock_mac": "Lock Mac",
    "new_trap_lock_data": "LockData",
    "new_trap_lock_associate": "Associate",
    "new_trap_lock_open": "Open",
    "new_trap_lock_close": "Close",
    "locks_name": "Locks",
    "login_init": "Login",
    "dialog_attention": "Attention",
    "recover_change": "Save",
    "recover_title": "Recover password",
    "recover_email": "Email",
    "recover_new_password": "New password",
    "recover_hint": "Intro your email",
    "recover_otp_email": "Intro a new password",
    "recover_otp_confirm_email": "Confirm password",
    "recover_go": "Recover",
    "recover_otp": "Intro your temporal password",
    "recover_otp_help": "A Email was sent with a temporal password",
    "check_email": "Intro your email",
    "check_otp": "Intro el unique code",
    "check_password": "Intro your password",
    "check_password_confirm": "Confirm your password",
    "change_password": "Password change sucessful",
    "exit_title": "Attention",
    "exit_message": "You will exit from Yup.city",
    "dialog_ok": "Ok",
    "dialog_cancel": "Cancel",
    "dialog_sucess": "Success!",
    "login_title": "Hey",
    "login_message": "It's nice\n to see you!",
    "login_recover": "Recover Password",
    "login_register": "Register",
    "login_login": "Login",
    "textfield_name": "Name",
    "textfield_email": "Email",
    "textfield_password": "Password",
    "textfield_telephone": "Telephone",
    "textfield_confirmpassword": "Confirm Password",
  };

  static const _allValues = {
    "es": _esValues,
    "en": _enValues,
  };

  I18n(Locale locale) : _locale = locale {
    _localizedValues = {};
  }

  final Locale _locale;

  static I18n of(BuildContext context) =>
      Localizations.of<I18n>(context, I18n)!;

  String _getText(String key) => _localizedValues[key] ?? '** $key not found';

  Locale get currentLocale => _locale;

  String get currentLanguage => _locale.languageCode;

  static Future<I18n> load(Locale locale) async {
    final translations = I18n(locale);
    _localizedValues = _allValues[locale.toString()]!;
    return translations;
  }
}

class I18nDelegate extends LocalizationsDelegate<I18n> {
  const I18nDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('es'),
    Locale('en'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<I18n> load(Locale locale) => I18n.load(locale);

  @override
  bool shouldReload(I18nDelegate old) => false;
}
